CREATE TABLE IF NOT EXISTS listings (
  id SERIAL PRIMARY KEY,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT DEFAULT 'CA',
  zip TEXT,
  price INTEGER,
  status TEXT DEFAULT 'Active',
  property_type TEXT DEFAULT 'Residential',
  property_sub_type TEXT,
  beds INTEGER,
  baths_full INTEGER DEFAULT 0,
  baths_half INTEGER DEFAULT 0,
  baths_three_quarter INTEGER DEFAULT 0,
  sqft INTEGER,
  price_per_sqft NUMERIC(10,2),
  year_built INTEGER,
  listing_id TEXT,
  days_on_mls INTEGER DEFAULT 0,
  subdivision TEXT,
  lot_size TEXT,
  garage_spaces INTEGER DEFAULT 0,
  levels TEXT,
  description TEXT,
  directions TEXT,
  parking TEXT,
  laundry TEXT,
  cooling TEXT,
  heating TEXT,
  fireplace TEXT,
  patio_porch TEXT,
  pool TEXT,
  view_description TEXT,
  sewer TEXT,
  eating_area TEXT,
  appliances TEXT,
  interior_features TEXT,
  flooring TEXT,
  association_fee NUMERIC(10,2),
  association_fee_frequency TEXT,
  high_school_district TEXT,
  mls_area TEXT,
  county TEXT DEFAULT 'Orange',
  assessments TEXT,
  tax_annual_amount NUMERIC(10,2),
  listing_agent TEXT,
  listing_office TEXT,
  special_conditions TEXT,
  open_house_date TEXT,
  open_house_time TEXT,
  is_new_listing BOOLEAN DEFAULT false,
  photos TEXT[] DEFAULT '{}',
  original_price INTEGER,
  land_lease TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
